name: musify
description: Music Streaming and Downloading app made in Flutter!

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.6.0+35

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ^3.3.7

dependencies:
  audio_service: ^0.18.7
  audio_session: ^0.1.10
  cached_network_image: ^3.2.2
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_downloader: ^1.9.0
  flutter_localizations: 
    sdk: flutter
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl:
  just_audio: ^0.9.30
  material_design_icons_flutter: ^5.0.6996
  on_audio_query: ^2.6.1
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  url_launcher: ^6.1.6
  youtube_explode_dart: ^1.12.1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.13
  flutter_test:
    sdk: flutter

flutter:

  generate: true
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf

  assets:
    - assets/db/playlists.db.json


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash2.png
  color_dark: "#151515"
  image_dark: assets/images/splash2.png

  android_12:
    image: assets/images/splash2.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash2.png
    icon_background_color_dark: "#151515"


flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_round: "assets/images/ic_launcher_round.png"
  image_path: "assets/images/ic_launcher.png"
  ios: true

